config/routes.rb
Rails.application.routes.draw do

  get 'etag/index'

  get  'set_tracking',                          to: 'set_tracking#prepare'
  post 'set_tracking',                          to: 'set_tracking#track'
  get 'set_tracking/set_hsts_header/:duration', to: 'set_tracking#set_hsts_header'

  get 'show_tracking',                                       to: 'show_tracking#collect_data'
  get 'show_tracking/display_data',                          to: 'show_tracking#display_data'
  get 'show_tracking/check_hsts/:index/:tracked_session_id', to: 'show_tracking#check_hsts'
  get 'show_tracking/check_local_storage/',                  to: 'show_tracking#check_local_storage'

  get 'etag',   to: 'etag#index'

  get 'redirection',                    to: 'redirection#set_tracking'
  get 'redirection/:redirection_token', to: 'redirection#get_tracking'

  post 'hpkp-report',   to: 'hpkp#report'

  get 'faq', to:'about_tracking#index'

  devise_for :users
  # Since we disabled rails normal js, we can't use the DELETE route, so we need a GET one
  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end


  root 'base#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  def index
  end
end

app/helpers/base_helper.rb
module BaseHelper
end

app/views/base/index.html.erb
<% if user_signed_in? %>
    <%= button_to('Start tracking me !', set_tracking_path, method: :get) %>
<% else %>
  <p>Please sign up to enjoy your tracking experience !</p>
<% end %>
  <%= button_to('Show me how you can recognise me !', show_tracking_path, method: :get) %> 
  <%= button_to('Learn more', faq_path, method: :get) %>
</div>