config/routes.rb
Rails.application.routes.draw do

  get 'etag/index'

  get  'set_tracking',                          to: 'set_tracking#prepare'
  post 'set_tracking',                          to: 'set_tracking#track'
  get 'set_tracking/set_hsts_header/:duration', to: 'set_tracking#set_hsts_header'

  get 'show_tracking',                                       to: 'show_tracking#collect_data'
  get 'show_tracking/display_data',                          to: 'show_tracking#display_data'
  get 'show_tracking/check_hsts/:index/:tracked_session_id', to: 'show_tracking#check_hsts'
  get 'show_tracking/check_local_storage/',                  to: 'show_tracking#check_local_storage'

  get 'etag',   to: 'etag#index'

  get 'redirection',                    to: 'redirection#set_tracking'
  get 'redirection/:redirection_token', to: 'redirection#get_tracking'

  post 'hpkp-report',   to: 'hpkp#report'

  get 'faq', to:'about_tracking#index'

  devise_for :users
  # Since we disabled rails normal js, we can't use the DELETE route, so we need a GET one
  devise_scope :user do
    get 'users/sign_out', to: 'devise/sessions#destroy'
  end


  root 'base#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/show_tracking_controller.rb
class ShowTrackingController < ApplicationController

  def collect_data
    # NB : we prefer creating a new one every time, just in case the session lasts longer than the tracking
    @tracked_session = TrackedSession.new(session_id: request.session_options[:id])

    @hsts_domain_list = Hsts::HSTS_URL_LIST

    check_first_party_cookie

    @tracked_session.save!

    # This is used to find the correct session in some tracking methods
    session[:tracked_session_id] = @tracked_session.id
    p 'show_tracking_controller'
    p request.session_options[:id]
    p @tracked_session.id
  end

  # NB : The view generates a call to this endpoint per hsts subdomain
  def check_hsts
    @tracked_session = TrackedSession.where(id: params[:tracked_session_id]).last
    if request.headers['X-https'] == 'true'
      # We received the request in https thanks to HSTS, so we need to write it to @tracked_session
      TrackedSessionHstsEntry.create(tracked_session: @tracked_session, url_index: params[:index])
    end
    head :no_content
  end

  # NB : The view generates a call to this endpoint
  def check_local_storage
    @tracked_session = TrackedSession.where(id: params[:id]).last
    local_storage = LocalStorage.find_by(token: params[:token])
    @tracked_session.local_storage = local_storage
    @tracked_session.save
  end

  def display_data
    @tracked_session = TrackedSession.where(session_id: request.session_options[:id]).last
    # Recover all the information about the different tracking methods
    @methods = {}

    # 1st-party cookie
    @methods[:first_party_cookie] = extract_data(FirstPartyCookie.find_by(token: cookies[:tracker]), 'First party Cookie', '#cookies')

    # LocalStorage
    @methods[:local_storage] = extract_data(@tracked_session.local_storage, 'Local Storage', '#lstorage')

    # HSTS
    @methods[:hsts] = extract_data(@tracked_session.hsts, 'HSTS cache', '#hsts')

    # ETag
    @methods[:etag] = extract_data(@tracked_session.etag, 'ETag cache', '#etag')

    # HPKP
    if Settings.hpkp_enabled
      @methods[:hpkp] = extract_data(@tracked_session.hpkp, 'HPKP cache', '#hpkp')
    end
    # HPKP
    @methods[:redirection] = extract_data(@tracked_session.redirection, 'Redirection cache', '#redirect')
  end

  private

  def check_first_party_cookie
    @tracked_session.first_party_cookie = FirstPartyCookie.find_by(token: cookies[:tracker])
  end

  def extract_data(object, display_name, anchor_name)
    {
      name:       display_name,
      worked:     ! object.nil?, # Do we think we found a tracked user ?
      correct:    user_signed_in? && current_user == object&.user, # Is it the user currently logged in ?
      created_at: object&.created_at,
      shortname: anchor_name
    }
  end
end

app/helpers/show_tracking_helper.rb
module ShowTrackingHelper
end

app/views/show_tracking/collect_data.html.erb
<meta http-equiv="refresh" content="<%= Settings.redirection_delay %>; url=<%= show_tracking_display_data_path %>"/>

<div style="display:none">
  <script>
  a = new XMLHttpRequest();
  a.open("GET","/show_tracking/check_local_storage?token="+localStorage.tracker+"&id=<%= @tracked_session.id %>");
  a.send();
  </script>
  <% if @hsts_domain_list %>
    <% @hsts_domain_list.each_with_index do |domain, index| %>
      <img alt="HSTS tracking" src="http://<%= domain %>/show_tracking/check_hsts/<%= index %>/<%= @tracked_session.id %>"></iframe>
    <% end %>
  <% end %>

  <img alt="ETag tracking" src="<%= "https://#{Settings.main_domain}/etag" %>"/>
  <link rel="stylesheet" media="all" href="<%= redirection_path %>">
</div>

<p>
  We're collecting the tracking data in your browser, you should soon be redirected to the <%= link_to('results page', show_tracking_display_data_path) %>.
</p>

app/views/show_tracking/display_data.html.erb
<h1> List of tracking methods </h1>

<p>
  Here you can see a list of the tracking methods, and which ones allowed us to track your browser.<br/>
  Please note that to prevent any enumeration of user email addresses, we do not display them, we only say whether it is the currently logged in user or not.
</p>

<table>
  <tr>
    <th> Tracking method </th>
    <th> Does this track someone ? </th>
    <% if user_signed_in? %>
      <th> Is it you ? </th>
    <% end %>
    <th> Set at : </th>
    <th> See more details </th>
  </tr>
  <% @methods.each do |key,method| %>
    <tr>
      <td> <%= method[:name] %> </td>
      <td> <%= method[:worked] %> </td>
      <% if user_signed_in? %>
        <td> <%= method[:correct] %> </td>
      <% end %>
      <td> <time><%= method[:created_at] %></time> </td>
      <td> <%= link_to('FAQ', faq_path + method[:shortname], method: :get) %> </td>
    </tr>
  <% end %>
</table>
<script>
for(let o of document.getElementsByTagName("time")) { if(o.innerText) {d = new Date(o.innerText.replace(" UTC",""));o.innerText = d.toLocaleDateString() + " " + d.toLocaleTimeString()}}
</script>
<%= button_to('Back', root_path, method: :get) %>

app/views/show_tracking/index.html.erb
<h1> List of tracking methods </h1>

<p> <%= link_to('Back', root_path) %> </p>

<table>
  <tr>
    <th> Tracking method </th>
    <th> Working ? </th>
    <th> Set at : </th>
  </tr>
  <% @methods.each do |key,method| %>
    <tr>
      <td> <%= method[:name] %> </td>
      <td> <%= method[:worked] %> </td>
      <td> <%= method[:created_at] %> </td>
    </tr>
  <% end %>
</table>
<%# This is updating client-side the value for LocalStorage %>
<script>
if (localStorage.getItem("tracker") == "<%= current_user.local_storages.last %>") {
  rowList = document.getElementsByTagName("tbody")[0].children
  for(i = 0; i < rowList.length; i++) {
    if(/Local Storage/.test(rowList[i].innerText)) {
      rowList[i].children[1].innerHTML = "true"
      rowList[i].children[2].innerHTML = "<%= current_user.local_storages.last.created_at %>"
      break;
    }
  }
}
</script>